version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    - requirements: docs-sphinx/requirements.txt

sphinx:
  configuration: docs-sphinx/conf.py
  fail_on_warning: true
