FROM debian:11-slim AS build

ARG BYTEWAX_VERSION

RUN apt-get update && \
    apt-get install --no-install-suggests --no-install-recommends --yes python3-venv gcc libpython3-dev && \
    python3 -m venv /venv && \
    /venv/bin/pip install --upgrade pip setuptools wheel

RUN /venv/bin/pip3 install bytewax==$BYTEWAX_VERSION

FROM gcr.io/distroless/python3-debian11:debug
COPY --from=build /venv /venv
WORKDIR /bytewax
COPY ./entrypoint.sh .
