#!/bin/sh

cd $BYTEWAX_WORKDIR
/venv/bin/python $BYTEWAX_PYTHON_FILE_PATH -w $BYTEWAX_WORKERS_PER_PROCESS -h $BYTEWAX_HOSTFILE_PATH -n $BYTEWAX_REPLICAS -p $(echo $BYTEWAX_POD_NAME | sed "s/$BYTEWAX_STATEFULSET_NAME-//g")