name: benchmarks

on:
  push:
    branches:
      - "main"
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v8.1.0
        with:
          version: "0.11.11"
          python-version: "3.12"
          activate-environment: true
          venv-path: venv
      - uses: dsherret/rust-toolchain-file@v1
      - uses: extractions/setup-just@v2
      - name: Prep build venv
        shell: bash
        run: uv pip sync --strict requirements/build-py3.12.txt
      - name: Build wheel
        shell: bash
        run: just build
      - name: Run benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: |
            WHEEL_FILE=$(ls ./dist/*.whl)
            uv pip install -v --no-deps $WHEEL_FILE
            just test-benchmark
